apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    {{- include "helm-s.labels" . | nindent 4 }}
  name: {{ .Values.service.name | quote }}
spec:
  selector:
    {{- include "helm-s.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  - name: stockmanager
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}