apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    {{- include "helm-p.labels" . | nindent 4 }}
  name: {{ .Values.service.name | quote }}
spec:
  selector:
    {{- include "helm-p.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  - name: productcatalogue
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}